### ISSUE TITLE
multi-gpu problem

### ISSUE THREAD

**Issue by mnikitin** [wkcn/LookaheadOptimizer-mx#4]
Hello!

Thanks for your mxnet implementation of lookahead optimizer!
I found that it crashes in multi-gpu setting, and the reason is that lookahead weights and weights to be updated can be placed on different gpu devices.
It can be fixed by replacing [this](https://github.com/wkcn/LookaheadOptimizer-mx/blob/master/optimizer.py#L41) line with this one:
`old_weight = self._lookahead_params[index].as_in_context(weight.context)`

**Comment by wkcn** [comment]
Thank you! I will fix it.

**Comment by wkcn** [comment]
Thank you!
